--多表插入

SET ECHO OFF     
SET feedback off 

DROP TABLE S_CUST;
DROP TABLE M_CUST;
DROP TABLE L_CUST;
DROP TABLE CUST;
DROP TABLE NEW_CUST;

CREATE TABLE S_CUST (
	ID NUMBER,
	SUM_ORDERS NUMBER
);

CREATE TABLE M_CUST (
	ID NUMBER,
	SUM_ORDERS NUMBER
);

CREATE TABLE L_CUST (
	ID NUMBER,
	SUM_ORDERS NUMBER
);

CREATE TABLE CUST (
	ID NUMBER,
	SUM_ORDERS NUMBER
);

CREATE TABLE NEW_CUST (
	ID NUMBER,
	SUM_ORDERS NUMBER
);

INSERT INTO CUST VALUES (1, 200);
INSERT INTO CUST VALUES (2, 600);
INSERT INTO CUST VALUES (3, 1600);
INSERT INTO CUST VALUES (4, 1800);
INSERT INTO CUST VALUES (5, 2000);
INSERT INTO CUST VALUES (6, 3000);
INSERT INTO CUST VALUES (7, 3100);
INSERT INTO CUST VALUES (8, 4500);

-- INSERT FIRST
INSERT FIRST
		WHEN SUM_ORDERS < 1000 THEN INTO S_CUST
		WHEN SUM_ORDERS >= 1000 AND SUM_ORDERS <= 2000 THEN INTO M_CUST
		WHEN SUM_ORDERS > 1000 AND SUM_ORDERS <= 4000 THEN INTO L_CUST 
	SELECT * FROM CUST;

SELECT * FROM S_CUST;
SELECT * FROM M_CUST;
SELECT * FROM L_CUST;
SELECT * FROM NEW_CUST;

TRUNCATE TABLE S_CUST;
TRUNCATE TABLE M_CUST;
TRUNCATE TABLE L_CUST;
TRUNCATE TABLE NEW_CUST;

-- INSERT ALL
INSERT ALL
		WHEN SUM_ORDERS < 1000 THEN INTO S_CUST
		WHEN SUM_ORDERS >= 1000 AND SUM_ORDERS <= 2000 THEN INTO M_CUST
		WHEN SUM_ORDERS > 1000 AND SUM_ORDERS <= 4000 THEN INTO L_CUST
		WHEN 1=1 THEN INTO NEW_CUST
	SELECT * FROM CUST;
	
SELECT * FROM S_CUST;
SELECT * FROM M_CUST;
SELECT * FROM L_CUST;
SELECT * FROM NEW_CUST;

