CREATE TABLE products (
	product_id NUMBER(6) CONSTRAINT prod_id_pk PRIMARY KEY,
	product_name VARCHAR2(15)
);

SELECT INDEX_NAME, INDEX_TYPE, UNIQUENESS 
	FROM USER_INDEXES 
	WHERE TABLE_NAME = 'PRODUCTS';
